name       : neochat
version    : 23.04.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/neochat-23.04.2.tar.xz : f422ed5ea1b7df39817fd1ffd2da2b8fa2da65b7bdfc2a34e57912b012af0960
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
component  : network.im
summary    : Neochat is a client for Matrix, the decentralized communication protocol for instant messaging.
description: |
    Neochat is a client for Matrix, the decentralized communication protocol for instant messaging.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Sql)
    - pkgconfig(olm)
    - pkgconfig(Quotient)
    - pkgconfig(libcmark)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kirigami2-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kirigami-addons-devel
    - knotifications-devel
    - kquickimageeditor-devel
    - kwindowsystem-devel
    - qcoro-qt5-devel
    - qtkeychain-devel
    - qqc2-desktop-style-devel
    - sonnet-devel
    - openssl-11-devel
rundeps    :
    - kirigami2
    - kirigami-addons
    - kitemmodels
    - kquickimageeditor
    - syntax-highlighting
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
