name       : neochat
version    : '22.09'
release    : 4
source     :
    - https://cdn.download.kde.org/stable/plasma-mobile/22.09/neochat-22.09.tar.xz : 9135cc31196394dafbdff0ff011aef176b365036c226b6a4cc33e084763517c9
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
component  : network.im
summary    : Neochat is a client for Matrix, the decentralized communication protocol for instant messaging.
description: |
    Neochat is a client for Matrix, the decentralized communication protocol for instant messaging.
builddeps  :
    - pkgconfig(libcmark)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Quotient)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kirigami2-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - kquickimageeditor-devel
    - kwindowsystem-devel
    - qcoro-qt5-devel
    - qtkeychain-devel
    - qqc2-desktop-style-devel
rundeps    :
    - kirigami2
    - kitemmodels
    - kquickimageeditor
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
